### ISSUE TITLE
Query performance

### ISSUE THREAD

**Issue by quocthinhle** [dungngminh/QuanLyNhaXe_Maven#45]
Hello Dũng,
Mình thầy ứng dụng trong những case sử dụng như tìm vé, tìm tuyến thì dữ liệu load lên khá lâu, trải nghiệm người dùng chưa thật sự tốt. Dũng có cách nào cải thiện performance của ứng dụng không nhỉ?
Thanks in advance.

**Comment by dungngminh** [comment]
Bên mình đã fix các xử lí query từ HQL sang Native Query, đã test thử, tốc độ khá ổn, bên mình cũng chưa định nghiên cứu về cache nên chắc để vài bản update sau sẽ cập nhật
Cảm ơn bạn đã cho ý kiến.
